In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as stats 
from scipy.stats import zscore
import matplotlib.pyplot as plt
from windrose import WindroseAxes

In [2]:
#Loading the dataset
df = pd.read_csv("data/sierraleone-bumbuna.csv")

In [3]:
df.describe() #stat

,GHI,DNI,DHI,ModA,ModB,Tamb,RH,WS,WSgust,WSstdev,WD,WDstdev,BP,Cleaning,Precipitation,TModA,TModB,Comments
count,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,525600.000000,0.0
mean,201.957515,116.376337,113.720571,206.643095,198.114691,26.319394,79.448857,1.146113,1.691606,0.363823,133.044668,7.172220,999.876469,0.000967,0.004806,32.504263,32.593091,NaN
std,298.495150,218.652659,158.946032,300.896893,288.889073,4.398605,20.520775,1.239248,1.617053,0.295000,114.284792,7.535093,2.104419,0.031074,0.047556,12.434899,12.009161,NaN
min,-19.500000,-7.800000,-17.900000,0.000000,0.000000,12.300000,9.900000,0.000000,0.000000,0.000000,0.000000,0.000000,993.000000,0.000000,0.000000,10.700000,11.100000,NaN
25%,-2.800000,-0.300000,-3.800000,0.000000,0.000000,23.100000,68.700000,0.000000,0.000000,0.000000,0.000000,0.000000,999.000000,0.000000,0.000000,23.500000,23.800000,NaN
50%,0.300000,-0.100000,-0.100000,3.600000,3.400000,25.300000,85.400000,0.800000,1.600000,0.400000,161.500000,6.200000,1000.000000,0.000000,0.000000,26.600000,26.900000,NaN
75%,362.400000,107.000000,224.700000,359.500000,345.400000,29.400000,96.700000,2.000000,2.600000,0.600000,234.100000,12.000000,1001.000000,0.000000,0.000000,40.900000,41.300000,NaN
max,1499.000000,946.000000,892.000000,1507.000000,1473.000000,39.900000,100.000000,19.200000,23.900000,4.100000,360.000000,98.400000,1006.000000,1.000000,2.400000,72.800000,70.400000,NaN

In [4]:
df.isna().sum() #missing values

Timestamp             0
GHI                   0
DNI                   0
DHI                   0
ModA                  0
ModB                  0
Tamb                  0
RH                    0
WS                    0
WSgust                0
WSstdev               0
WD                    0
WDstdev               0
BP                    0
Cleaning              0
Precipitation         0
TModA                 0
TModB                 0
Comments         525600
dtype: int64

In [5]:
missing_percentage = df.isna().mean() * 100
high_null_columns = missing_percentage[missing_percentage > 5]

print("Columns with >5% missing values:")
print(high_null_columns)

Columns with >5% missing values:
Comments    100.0
dtype: float64

In [6]:
cols_to_check = ['GHI', 'DNI', 'DHI', 'ModA', 'ModB', 'WS', 'WSgust'] #outliers of these
z_scores = df[cols_to_check].apply(zscore)
outliers = (np.abs(z_scores) > 3)
print("Outlier counts per column (|Z| > 3):")
print(outliers.sum())

Outlier counts per column (|Z| > 3):
GHI       2477
DNI       7586
DHI       2986
ModA      1604
ModB      2041
WS        3967
WSgust    3665
dtype: int64

In [7]:
df[cols_to_check] = df[cols_to_check].mask(outliers) #make outliers NaN

In [8]:
df_clean = df.copy() #make missing values median
for col in cols_to_check:
    median_value = df_clean[col].median()
    df_clean[col] = df_clean[col].fillna(median_value)

In [9]:
df_clean.to_csv("data/sierraleone_clean.csv", index=False)

In [ ]:
df_clean['Timestamp'] = pd.to_datetime(df_clean['Timestamp'])

In [ ]:
plt.figure(figsize=(14, 7))

plt.plot(df_clean['Timestamp'], df_clean['GHI'], label='GHI')
plt.plot(df_clean['Timestamp'], df_clean['DNI'], label='DNI')
plt.plot(df_clean['Timestamp'], df_clean['DHI'], label='DHI')
plt.plot(df_clean['Timestamp'], df_clean['Tamb'], label='Tamb')

plt.xlabel('Timestamp')
plt.ylabel('Value')
plt.title('Solar Irradiance and Temperature Over Time')
plt.legend()
plt.show()

In [ ]:
df_clean['Month'] = df_clean['Timestamp'].dt.month

monthly_avg = df_clean.groupby('Month')[['GHI', 'DNI', 'DHI', 'Tamb']].mean()

monthly_avg.plot(kind='bar', figsize=(12, 6))
plt.title('Average Solar Irradiance and Temperature by Month')
plt.xlabel('Month')
plt.ylabel('Average Value')
plt.show()

In [ ]:
cols = ['GHI', 'DNI', 'DHI', 'Tamb']

# Compute z-scores
z_scores_clean = df_clean[cols].apply(zscore)

# Identify rows where any absolute z-score > 3
outliers_clean = (z_scores_clean.abs() > 3).any(axis=1)
df_outliers_clean = df_clean[outliers_clean]

In [ ]:
df_clean['Timestamp'] = pd.to_datetime(df_clean['Timestamp'])
df_clean.set_index('Timestamp', inplace=True)
df_outliers_clean.set_index('Timestamp', inplace=True)

In [ ]:
plt.figure(figsize=(12, 5))
sns.lineplot(data=df_clean, x=df_clean.index, y='GHI', label='GHI')
sns.scatterplot(data=df_outliers_clean, x=df_outliers_clean.index, y='GHI', color='red', label='Anomalies')
plt.title("GHI with Anomalies Highlighted")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(12, 5)) 
sns.lineplot(data=df_clean, x=df_clean.index, y='DNI', label='DNI')
sns.scatterplot(data=df_outliers_clean, x=df_outliers_clean.index, y='DNI', color='red', label='Anomalies')
plt.title("DNI with Anomalies Highlighted")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(12, 5))
sns.lineplot(data=df_clean, x=df_clean.index, y='DHI', label='DHI')
sns.scatterplot(data=df_outliers_clean, x=df_outliers_clean.index, y='DHI', color='red', label='Anomalies')
plt.title("DHI with Anomalies Highlighted")
plt.legend()
plt.show()

In [ ]:
plt.figure(figsize=(12, 5))
sns.lineplot(data=df_clean, x=df_clean.index, y='Tamb', label='Tamb')
sns.scatterplot(data=df_outliers_clean, x=df_outliers_clean.index, y='Tamb', color='red', label='Anomalies')
plt.title("Tamb with Anomalies Highlighted")
plt.legend()
plt.show()

In [ ]:
#Cleaning effect on ModA and ModB
cleaning_effect = df_clean.groupby('Cleaning')[['ModA', 'ModB']].mean().reset_index()

# Melt the dataframe for better Seaborn plotting
melted = cleaning_effect.melt(id_vars='Cleaning', value_vars=['ModA', 'ModB'],
                               var_name='Module', value_name='Average Irradiance')

# Plot
plt.figure(figsize=(8, 5))
sns.barplot(data=melted, x='Cleaning', y='Average Irradiance', hue='Module')
plt.title('Effect of Cleaning on ModA and ModB')
plt.xlabel('Cleaning (0 = Before, 1 = After)')
plt.ylabel('Average Irradiance')
plt.xticks([0, 1], ['Before Cleaning', 'After Cleaning'])
plt.tight_layout()
plt.show()

In [ ]:
#Heatmap of Correlations
corr_cols = ['GHI', 'DNI', 'DHI', 'TModA', 'TModB']
corr_matrix = df_clean[corr_cols].corr()

# Plot heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

In [ ]:
#Scatter plots: WS, WSgust, WD vs. GHI
# WS vs. GHI
sns.scatterplot(data=df_clean, x='WS', y='GHI', size=1, legend=False)
plt.title('Wind Speed (WS) vs GHI')
plt.show()

# WSgust vs. GHI
sns.scatterplot(data=df_clean, x='WSgust', y='GHI', size=1, legend=False)
plt.title('Wind Gust (WSgust) vs GHI')
plt.show()

# WD vs. GHI
sns.scatterplot(data=df_clean, x='WD', y='GHI', size=1, legend=False)
plt.title('Wind Direction (WD) vs GHI')
plt.show()

In [ ]:
# RH vs. Tamb
sns.scatterplot(data=df_clean, x='RH', y='Tamb', size=1, legend=False)
plt.title('Relative Humidity (RH) vs Temperature (Tamb)')
plt.show()

# RH vs. GHI
sns.scatterplot(data=df_clean, x='RH', y='GHI', size=1, legend=False)
plt.title('Relative Humidity (RH) vs GHI')
plt.show()

In [ ]:
#Wind rose or radial bar plot of WS/WD
df_wind = df_clean[['WS', 'WD']].dropna()

ax = WindroseAxes.from_ax()
ax.bar(df_wind['WD'], df_wind['WS'], normed=True, opening=0.8, edgecolor='white')
ax.set_legend()
plt.title('Wind Rose')
plt.show()

In [ ]:
#Histograms of of GHI and WS:
# Histogram for GHI
sns.histplot(df_clean['GHI'], kde=True, bins=30, color='orange')
plt.title('Distribution of GHI')
plt.xlabel('GHI')
plt.ylabel('Frequency')
plt.show()

# Histogram for WS
sns.histplot(df_clean['WS'], kde=True, bins=30, color='skyblue')
plt.title('Distribution of Wind Speed (WS)')
plt.xlabel('WS')
plt.ylabel('Frequency')
plt.show()

In [ ]:
#Relative humidity with temperature readings and solar radiation.

fig, axs = plt.subplots(2, 2, figsize=(14, 10), sharex=True)

# RH vs Tamb
sns.scatterplot(data=df_clean, x='RH', y='Tamb', ax=axs[0, 0])
axs[0, 0].set_title('RH vs Tamb')

# RH vs TModA
sns.scatterplot(data=df_clean, x='RH', y='TModA', ax=axs[0, 1])
axs[0, 1].set_title('RH vs TModA')

# RH vs TModB
sns.scatterplot(data=df_clean, x='RH', y='TModB', ax=axs[1, 0])
axs[1, 0].set_title('RH vs TModB')

# RH vs GHI
sns.scatterplot(data=df_clean, x='RH', y='GHI', ax=axs[1, 1])
axs[1, 1].set_title('RH vs GHI')

# Add a shared X label
for ax in axs.flat:
    ax.set_xlabel('Relative Humidity (%)')

plt.tight_layout()
plt.show()

In [ ]:
plt.figure(figsize=(10, 6))
sns.scatterplot(
    data=df_clean, 
    x='GHI', 
    y='Tamb', 
    size='RH', 
    sizes=(20, 200), 
    alpha=0.6
)
plt.title('GHI vs Tamb (Bubble size = RH)')
plt.xlabel('Global Horizontal Irradiance (GHI)')
plt.ylabel('Ambient Temperature (Tamb)')
plt.legend(title='Relative Humidity', loc='upper right')
plt.tight_layout()
plt.show()